[정렬] 9월 2일
Altu-Bitu-3/Altu-Bitu-BaeYuSun pull request #1
Opened 2022-09-02 14:52 UTC by Esther012

1431, 11651번 제출합니다.

2022-09-05 07:37 UTC, jaeseo222 reviewed
P2. **11651 코드 리뷰 완료**
안녕하세요 유선님 ☺️☺️ 코드도 너무 깔끔하고 주석도 작성해주셔서 리뷰 드리기 너무 좋았습니다!

간단한 코멘트 달았으니, 확인 부탁 드립니다 !
수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다!
감사합니다 🤗🤗

2022-09-05 07:37 UTC, jaeseo222 commented on [정렬] 9월 2일/11651.cpp
> +};
p2.
구조체를 선언해주셨네요!! x, y 처럼 직관적인 변수명은 참조할 때 헷갈리지 않는 장점이 있을 수 있죠!
이렇듯 구조체도 좋지만, **`pair`라는 두 개의 자료형을 하나로 묶어서 사용할 수 있는 Container도 있습니다.** 😄
`pair`은 **벡터에 자료형으로 선언**하여 2차원 배열처럼 사용하기도 하고, 현재 문제처럼 **좌표계**를 표현할 때 사용하기도 합니다. 아래 사용 방법 블로그를 첨부합니다!

📌 [pair 사용 방법](https://github.com/Altu-Bitu-3/Notice/blob/main/00.%20%EA%B0%95%EC%9D%98%EC%9E%90%EB%A3%8C/00.%20OT.pdf)


두 자료형을 하나로 묶어 사용할 때 **구조체** vs **pair** 둘 중 편한 걸로 사용해주시면 되며, 보통 코테에선 변수명을 선언해주지 않아도 되는 **pair** 을 사용합니다!

🔥🔥 그럼, `pair`을 `sort` 했을 땐 두 자료형 중 어느 것을 기준으로 정렬될까요? 이를 고려하여 **비교함수**를 구현해주시면 좋을 것 같습니다.

2022-09-05 08:36 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +}
sort 함수에서 역순(내림차순)으로 정렬을 하고 싶으실 때는  greater<>()를 사용하시면 됩니다!

2022-09-05 08:49 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +	int b[50] = { 0, };
p1.

코드는 정말 깔끔하게 잘 짜주셨는데 C++에서는 Array보다 Vector를 더 많이 사용합니다!
Vector가 선언이 간편하고 내장함수도 잘 되어 있어서 앞으로 과제에서는 Vector를 사용하실 일이 훨씬 많으실 거예요!
간단한 문제부터 Vector를 사용하는 연습을 해보면 어떨까요?
Vector 사용법은 슬랙 공지에 C++가이드 참고하시면 됩니다!!
다른 부분은 다 좋습니다:)

2022-09-05 08:55 UTC, jk0527 requested changes
p1.

코드는 정말 깔끔하게 잘 짜주셨습니다!
Vector가 선언이 간편하고 내장함수도 잘 되어 있어서 앞으로 과제에서는 Vector를 사용하실 일이 훨씬 많으실 거예요!
간단한 문제부터 Vector를 사용하는 연습을 해보면 어떨까요?
Vector 사용법은 슬랙 공지에 C++가이드 참고하시면 됩니다!!
다른 부분은 다 좋습니다:)

2022-09-05 08:55 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +}
sort 함수에서 역순(내림차순)으로 정렬을 하고 싶으실 때는 greater<>()를 사용하시면 됩니다!

2022-09-05 08:55 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +	int b[50] = { 0, };
C++에서는 Array보다 Vector를 더 많이 사용합니다!
a, b를 Vector를 이용하여 구현하는 연습을 하면 좋을 것 같아요!!

2022-09-08 12:15 UTC, Minseo10 approved these changes
**P3. 1431 코드리뷰 완료**
코드 깔끔하게 아주 잘 구현하셨어요! sum함수에서 샘플코드에 있는 isdigit()을 이용하는 방법도 한번 확인해 보시면 좋을 것 같아요~!! 수고하셨습니다😄

2022-09-08 12:15 UTC, Minseo10 commented on [정렬] 9월 2일/1431.cpp
> +	if (asum != bsum) return asum < bsum;
필수는 아니지만, if문에서 중괄호{} 를 사용해주시면 더 좋을 것 같아요~!

2022-09-08 12:15 UTC, Minseo10 commented on [정렬] 9월 2일/1431.cpp
> +		if (s[i] >= '0' && s[i] <= '9')
s[i] 가 문자 0과 9 사이에 있는지 확인하는 방식도 아주 좋지만, isdigit()함수를 이용하여 숫자인지 판별하는 방법이 있으니 참고하시면 좋을 것 같습니다! 😃

2022-09-09 05:53 UTC, bsa0322 reviewed
**p2. 1758 코드리뷰 완료**
유선님 안녕하세요 🥰 리뷰가 늦어 죄송합니다 😢
크게 수정하실 부분은 없지만, 클린 코드에 대한 코멘트 몇 가지 남겼으니 확인해주시면 좋을 것 같아요 🥰 첫 과제 너무 수고하셨습니다 ✨✨

2022-09-09 05:53 UTC, bsa0322 commented on [정렬] 9월 2일/1758.cpp
> +vector <int> line;
p2. 전역 변수 사용은 가급적 지양하는 것이 좋습니다! 알고리즘 문제 풀 때는 크게 상관 없을 수 있지만, 후에 협업을 한다고 생각하면, 전역변수로 선언한 변수를 지역변수로 다른 사람이 선언해버릴 수도 있고, 여러 군데에서 수정을 하면 충돌이 날 가능성도 높아지기 때문이죠! 그리고 코드의 가독성이 더 낮아지게 될거예요. 

물론 전역 변수를 쓰는 편이 더 좋은 경우도 많습니다! 여러 함수에서 사용하는 변수이거나, 재귀 함수 내에서 사용하는 변수일 등의 경우엔 메모리를 효율적으로 관리하기 위해 전역변수를 쓰는 것이 더 좋을 수도 있어요.

해당 문제는 line배열을 sum 함수에서만 사용하기 때문에, main에서 선언 후 **매개변수로 넘겨주도록** 짜보면 어떨까요?

2022-09-09 05:53 UTC, bsa0322 commented on [정렬] 9월 2일/1758.cpp
> +}
p2. 수민님께서 남겨주신 코멘트처럼, c++에서는 내림차순 정렬을 비교함수 없이 구현할 수 있어요!

2022-09-09 05:53 UTC, bsa0322 commented on [정렬] 9월 2일/1758.cpp
> +}
p3. 로직 완벽합니다~! 사소하지만, 연산 횟수를 아주 조금 더 줄일 수 있는 방법이 있는데요!
현재 팁들은 내림차순 정렬이 되어 있는 상태일 거예요. 그렇다면 음수가 되는 순간이 됐을 때, 그 이후의 순간들은 어떤 상황이 될까요?

2022-09-09 06:49 UTC, yuseon-bae commented on [정렬] 9월 2일/11651.cpp
> +};
@jaeseo222 

using namespace std;
typedef pair<int, int> cordinate;
bool compare(cordinate a, cordinate b) {
	if (a.first != b.first) return a.second < b.second; //y좌표가 다르면  좌표가 증가하는 순서대로 정렬
	if (a.first != b.first) return a.second < b.second; //x좌표가 다르면 좌표가 증가하는 순서대로 정렬
}

int main() {
	int n; 

	cin >> n;
	vector<cordinate> arr;

	for (int i = 0; i < n; i++) {
		cin >> arr[i].first >> arr[i].second;
	}

	sort(arr.begin(), arr.end(), compare);
	
	for (int i = 0; i < n; i++) {
		cout << arr[i].first <<" " << arr[i].second << "\n";
	}
}
이렇게 고쳐봤는데 계속 런타임에러(OutOfBounds)가 뜹니다. 어떻게 pair을 사용해야 하나요?

2022-09-09 07:05 UTC, Esther012 commented on [정렬] 9월 2일/1026.cpp
> +	int b[50] = { 0, };
int n;
	cin >> n;
	vector <int> a(50, 0);
	vector <int> b(50, 0);

	for (int i = 0; i < n; i++) {
		cin >> a[i];
	}
	for (int i = 0; i < n; i++) {
		cin >> b[i];
	}
이렇게 코드를 수정했는데 틀렸다고 뜹니다.
vector에 입력을 받을 때  무조건 push_back 함수를 사용하나요?
cin >> a[i]는 안 되는 건가요?

2022-09-10 02:36 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +	int b[50] = { 0, };
피드백이 늦어서 죄송합니다..ㅠ
cin>>a[i]를 사용하셔도 됩니다!!
그리고 Vector에서는 Array랑 다르게 n을 입력받아서 Vector의 크기를 바로 지정하는 것이 가능합니다!!
즉, vector a(n, 0)이렇게 하셔도 돼요!! (0은 생략해도 괜찮습니다!!)
틀린 부분은 vector를 사용할 때 vector**<자료형>** 이렇게 선언하셔야 하는데 자료형이 빠져서 그런 것 같아요!!
파일의 첫 부분에 #include <vector> 도 추가해야 하고요!!

2022-09-10 11:06 UTC, Esther012 commented on [정렬] 9월 2일/1026.cpp
> +	int b[50] = { 0, };
코드를 리뷰해주신 대로 수정했습니다~ 확인 부탁드립니다! 감사합니다!!

2022-09-10 14:51 UTC, jk0527 requested changes
p1. 

컴파일 오류가 나네요..! 제가 코멘트 드린 부분 살짝만 고치면 잘 돌아갈 것 같아요!! 모두 잘 고쳐주셨는데 말씀드린 부분만 더 신경써주시면 될 것 같아요!! 고치시고 리뷰어 호출해주세요!!😊😊

2022-09-10 14:51 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +		cin >> num;
num이 선언이 안되어 있어요!

2022-09-10 14:51 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +#include <algorithm>
vector도 include 해주셔야 해요!

2022-09-10 14:51 UTC, jk0527 commented on [정렬] 9월 2일/1026.cpp
> +	vector <int> a;
이건 그냥 스타일인데 여기서 a(n)이렇게 선언하고 입력받을 때 push_back 안 쓰고 바로 cin>>a[i]로 받으셔도 돼요!!

2022-09-10 15:33 UTC, jk0527 approved these changes

2022-09-10 15:34 UTC, jk0527 approved these changes
P3.
좋아요!! 이제 머지하셔도 될 것 같아요!! 고생하셨습니다!!😎😎

2022-09-10 15:35 UTC, merged

2022-09-14 15:33 UTC, jaeseo222 commented on [정렬] 9월 2일/11651.cpp
> +};
답변이 늦어 죄송합니다. 😭😭😭
arr에 초기화가 되어 있지 않네요! 초기화가 되어 있지 않은 상태에서 arr[i]에 접근하려니까 런타임 에러가 나는 문제가 발생했습니다!
다음과 같이 초기화 해주시면 될 것 같아요 😉😉
`vector<cordinate> arr(n, {0, 0});`