[브루트포스] 9월 21일
Altu-Bitu-3/Altu-Bitu-BaeYuSun pull request #6
Opened 2022-09-21 14:02 UTC by Esther012

#### 내용 & 질문
> 브루트포스 과제 제출합니다

#### <기존 제출>
> 1544, 2858, 14888

#### <추가 제출>
>

2022-09-21 19:36 UTC, dbswn approved these changes
**P2 14888 코드리뷰 완료**

안녕하세요 유선님 😄😄 코드도 너무 깔끔하고 주석도 작성해주셔서 리뷰 드리기 너무 좋았습니다!!!

간단한 코멘트 달았으니, 확인 부탁 드립니다 !**수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다!** 수고 많으셨습니다.감사합니다. 🤗🤗

2022-09-21 19:36 UTC, dbswn commented on [브루트포스] 9월 16일/14888.cpp
> +#define MAX 1000000000
**P3**
c++에서 10의 배수 숫자 표현할 때, 1e(지수) 형태로 표현하면 간단하게 쓸 수 있습니다!

2022-09-21 19:36 UTC, dbswn commented on [브루트포스] 9월 16일/14888.cpp
> +int oper[4];
**P3**
배열 사용은 vector로 통일하면 어떨까요?!

2022-09-21 19:36 UTC, dbswn commented on [브루트포스] 9월 16일/14888.cpp
> +		if (ma > result) ma = result;
**P2**
c++ iostream 헤더에서 제공하는 max, min 함수 사용해서 코드 줄이면 어떨까요?

2022-09-21 19:36 UTC, dbswn commented on [브루트포스] 9월 16일/14888.cpp
> +				calcul(result / num[count], count + 1);
**P2**
조건 나눠서 재귀함수 따로 불러주신 형태도 좋지만, 연산자에 따라 계산하는 부분을 함수화해서 결과를 리턴받은 다음, 재귀 호출하는 코드는 한 줄로 통일해서 쓰면 어떨까요?!

2022-09-22 14:39 UTC, bsa0322 requested changes
**p1. 2858 코드리뷰 완료**
유선님 안녕하세요 😊 주석 설명을 잘 써주셔서 잘 봤습니다~! 함수화 해주신 것도 너무 좋은데, 함수화 할 때 주의해야 할 중요한 부분에 대해 코멘트 남겼으니 확인 후 수정해주시면 좋을 것 같아요! 더불어 문제의 효율성 관련해서도 코멘트 남겼습니다. 수정 후, 리뷰어로 다시 호출 부탁드려요~! 수고하셨습니다 🥰🥰🥰

2022-09-22 14:39 UTC, bsa0322 commented on [브루트포스] 9월 16일/2858.cpp
> +}
p1. 가로, 세로 길이의 최소가 3이라는 점을 활용해서 브루트 포스적 접근을 아주 잘 해주셨네요!! 
지금도 좋지만, **해당 문제는 O(N) 으로 해결**할 수도 있어요.

깃허브 힌트로 **타일의 총 개수는 타일의 넓이**와 같을 거라 말씀드렸죠~! 저희는 직사각형의 넓이를 안다면, **가로와 세로 둘 중 하나의 길이만 알아도 다른 길이를 알 수가 있어요!** 그리고 가로와 세로 길이를 알면 지금처럼 빨간 타일과 갈색 타일의 개수를 구해 정답과 일치하는지 알 수 있겠죠 🥰 그리고 이때는, 직사각형의 넓이에 맞춰 가로와 세로의 길이를 구했을 테니까 **두 타일 중 하나만 비교해도 괜찮을 것 같아요.**

힌트 더 필요하시면 말씀해주세요~!

p1. 더불어 출력은 가급적 main함수에서 진행해주시는 편이 좋아요!! 디버깅을 위한 출력 코드가 아닌 이상, **함수는 용도가 명확하게** (지금으로 예를 들면 가로와 세로 길이를 구하는 함수) 해서 **구한 정답은 리턴하는 형태**가 나중에 함수의 재활용도도 높아지고, 가독성도 높일 수 있습니다!! 
함수 내에 출력이 있다면, 나는 해당 함수에서 딱 정답만 구하고 싶은건데 계속 출력이 돼서 곤란한 상황이 생길 수도 있겠죠 😂

지금 함수화 해주신 거 좋지만, 위의 코멘트 참고해서 리턴형이 있도록 작성하면 좋을 것 같아요~! 값이 2개여서 리턴형이 애매하다면 **c++의 pair 클래스**에 대해 알아보셔도 좋을 것 같습니다 🥰

2022-09-22 19:24 UTC, jaeseo222 reviewed
**p2. 1544 코드 리뷰 완료**

안녕하세요 유선님 🦕🦕
너무 잘 풀어주시고,, 함수화로 코드도 깔끔할 뿐더러 주석도 정성스레 작성해주셔서 리뷰 드리기 너무 좋았습니다!!
간단한 코멘트 달았으니, 확인 부탁 드립니다 !
**수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다!** 수고 많으셨습니다.
감사합니다.🤗🤗

2022-09-22 19:24 UTC, jaeseo222 commented on [브루트포스] 9월 16일/1544.cpp
> +    }
p2. vector로 서로 다른 단어를 잘 담아주셨네요!! 이것도 좋지만, 서로 다른 단어니까 **중복된 요소를 허용하지 않는 자료구조**도 있었죠~!
이 자료구조에는 **찾으려는 요소가 존재하는지 확인하는 함수**도 제공됩니다!

이 함수를 활용하여 `same` 플래그 변수를 생략해볼 수 있지 않을까요??🔥🔥

2022-09-25 15:59 UTC, bsa0322 approved these changes
2858 수정해주신 거 확인했습니다! 수고하셨습니다~!! 🥰🥰🥰

2022-09-26 03:02 UTC, merged